In [1]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt
import time
import mediapipe as mp
import pandas as pd

# 6. Preprocess Data and Create Labels and Features

In [2]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [3]:
df = pd.read_csv(f"https://docs.google.com/spreadsheets/d/1FcGVkGoaUH1eb0cs9Ip3Y2tfxv7a2GfEzXV7FMk0vV8/export?format=csv")

actions =  np.array(list(df["actions"]))
label_map = {label:num for num, label in enumerate(actions)}

DATA_PATH = os.path.join('StoreData') 
# DATA_PATH = os.path.join('MP_Data') 
# Videos are going to be 30 frames in length
sequence_length = 30

In [4]:
actions.shape[0]

3

In [5]:
sequences, labels = [], []
for action in actions:
    for sequence in np.array(os.listdir(os.path.join(DATA_PATH, action))).astype(int):
        window = []
        for frame_num in range(sequence_length):
            res = np.load(os.path.join(DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

In [6]:
sequences

[[array([ 0.63940382,  0.23236614, -0.46760672, ...,  0.        ,
          0.        ,  0.        ]),
  array([ 0.50658286,  0.22456758, -0.35736251, ...,  0.33693781,
          0.27753103, -0.02053747]),
  array([ 0.492174  ,  0.22061369, -0.40889448, ...,  0.33454156,
          0.27788809, -0.01946517]),
  array([ 0.49433702,  0.21238378, -0.32980034, ...,  0.32634401,
          0.28290543, -0.01891863]),
  array([ 0.49051422,  0.21331316, -0.36987656, ...,  0.32723954,
          0.28432345, -0.01936157]),
  array([ 0.48883224,  0.21369664, -0.37792861, ...,  0.32638195,
          0.28367159, -0.01682102]),
  array([ 0.48727098,  0.21406887, -0.34523636, ...,  0.32640636,
          0.28521466, -0.0174471 ]),
  array([ 0.48713645,  0.21435481, -0.35042173, ...,  0.32547405,
          0.28405714, -0.01814333]),
  array([ 0.48962727,  0.21389832, -0.34856319, ...,  0.32842666,
          0.28275108, -0.0203524 ]),
  array([ 0.49180493,  0.21379983, -0.35082421, ...,  0.35160664,
       

In [7]:
np.array(sequences).shape

(90, 30, 1662)

In [8]:
np.array(labels).shape

(90,)

In [9]:
X = np.array(sequences)

In [10]:
X.shape

(90, 30, 1662)

In [11]:
y = to_categorical(labels).astype(int)

In [12]:
y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05)

In [14]:
# y_test.shape
X_train

array([[[ 0.52335691,  0.19512329, -0.28993249, ...,  0.        ,
          0.        ,  0.        ],
        [ 0.52827102,  0.19512831, -0.36037913, ...,  0.35786316,
          0.22468205, -0.01463094],
        [ 0.52928799,  0.19530517, -0.40834504, ...,  0.35848519,
          0.22303581, -0.01857051],
        ...,
        [ 0.52690935,  0.19836706, -0.34097731, ...,  0.35324496,
          0.22885078, -0.0181008 ],
        [ 0.52613395,  0.19836336, -0.34161678, ...,  0.35279307,
          0.22931376, -0.01885405],
        [ 0.52591765,  0.19871496, -0.33522516, ...,  0.35288969,
          0.22832993, -0.01855613]],

       [[ 0.50478065,  0.21521929, -0.28052211, ...,  0.51828706,
          0.41210359, -0.04430681],
        [ 0.50719106,  0.2152178 , -0.28533572, ...,  0.49056298,
          0.41813779, -0.04012909],
        [ 0.50942624,  0.21544422, -0.28331032, ...,  0.49204087,
          0.39888826, -0.03181378],
        ...,
        [ 0.50886983,  0.20711337, -0.2452912 , ...,  

# 7. Build and Train LSTM Neural Network

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import TensorBoard

In [16]:
log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log_dir)

In [17]:
model = Sequential()
model.add(LSTM(64, return_sequences=True, activation='relu', input_shape=(30,1662)))
model.add(LSTM(128, return_sequences=True, activation='relu'))
model.add(LSTM(64, return_sequences=False, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(actions.shape[0], activation='softmax'))

In [18]:
res = [0.7,0.2,0.1]

In [19]:
res

[0.7, 0.2, 0.1]

In [20]:
actions[np.argmax(res)]

'hello'

In [21]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [23]:
model.fit(X_train, y_train, epochs=2000, callbacks=[tb_callback])

Epoch 1/2000
3/3 [==============================] - 0s 120ms/step - loss: 0.4201 - categorical_accuracy: 0.8353
Epoch 2/2000
3/3 [==============================] - 0s 136ms/step - loss: 0.3527 - categorical_accuracy: 0.9412
Epoch 3/2000
3/3 [==============================] - 0s 112ms/step - loss: 0.2693 - categorical_accuracy: 0.9412
Epoch 4/2000
3/3 [==============================] - 1s 300ms/step - loss: 0.3001 - categorical_accuracy: 0.8471
Epoch 5/2000
3/3 [==============================] - 1s 326ms/step - loss: 0.2979 - categorical_accuracy: 0.8706
Epoch 6/2000
3/3 [==============================] - 1s 229ms/step - loss: 0.3888 - categorical_accuracy: 0.8588
Epoch 7/2000
3/3 [==============================] - 0s 182ms/step - loss: 0.5150 - categorical_accuracy: 0.7176
Epoch 8/2000
3/3 [==============================] - 0s 185ms/step - loss: 0.3395 - categorical_accuracy: 0.9059
Epoch 9/2000
3/3 [==============================] - 0s 168ms/step - loss: 0.2345 - categorical_accuracy:

KeyboardInterrupt: 

# 9. Save Weights

In [32]:
model.save('action.h5')

In [ ]:
del model

In [ ]:
model.load_weights('action.h5')